### ISSUE TITLE
Default encryption method

### ISSUE THREAD

**Issue by JFOC** [stymiee/php-simple-encryption#1]
hi,
so we need to call this getEncryptionObject first ??
having a default one will be better, and setting the encryption method into something setEncryptionObject is better if we do not want to use the default encryption method.

**Comment by stymiee** [comment]
I am unsure what you mean by, "having a default one will be better". There is a default encryption object which uses a currently recommended cipher. This is by design as the primary focus of this library is to be secure by default.

If you do not want to use the default encryption cipher you can change it simply by passing the name of the cipher you wish to use:

    $encryption = Encryption::getEncryptionObject('AES-256-CBC');
